### ISSUE TITLE
makefile danger

### ISSUE THREAD

**Issue by theroot79** [RehabMan/OS-X-ACPI-Debug#2]
On "makefile" file ,  line 37,44:
`rm -Rf $(INSTDIR)/$(KEXT)`
Double check these two variables are they empty, otherwise someone ( like me ) will endup with deleted harddrive in few minutes !!!!!!!!!!!

**Comment by RehabMan** [comment]
Both INSTDIR and KEXT are set by the makefile

```
KEXT=ACPIDebug.kext
...
VERSION_ERA=$(shell ./print_version.sh)
ifeq "$(VERSION_ERA)" "10.10-"
	INSTDIR=/System/Library/Extensions
else
	INSTDIR=/Library/Extensions
endif
``
